# Generated by Django 2.0.5 on 2018-08-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='availibility',
            new_name='availability',
        ),
    ]
