# Generated by Django 2.0.5 on 2018-08-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180802_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='package_actions',
        ),
    ]
