# Generated by Django 2.1.1 on 2018-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='count',
        ),
        migrations.AddField(
            model_name='poke',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
