# Generated by Django 2.1.1 on 2018-09-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180921_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='user',
        ),
        migrations.AddField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokedpokes', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokerpokes', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poke',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
